var form = document.createElement("form");
form.setAttribute("action", "https://www.discogs.com/user/demr_awd/collection");
form.setAttribute("method", "post");
form.setAttribute("id", "random_list_form");
var input = document.createElement("input");
input.setAttribute("name", "Action.RandomItem");
input.setAttribute("value", "Random Item");
input.setAttribute("type", "hidden");
form.appendChild(input);
document.body.appendChild(form);
document.querySelector('#random_list_form').submit();
